# Generated by Django 5.1.2 on 2024-11-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='role_id',
            new_name='role',
        ),
    ]
