# Generated by Django 5.1.2 on 2024-11-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='project_id',
            new_name='project',
        ),
    ]
